spring.application.name=spring-boot-library-boi-sync
#docker command
#PS E:\Baust Notes\All projects\Library-App\fullstack-library-app\SPRINGBOOT-LIBRARY-BACKEND\spring-boot-library-boi-sync> docker run -d -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=BoiSyncDB --name BoiSyncDB -p 3308:3306 mysql:8.0
#266312ffb0828d04456a244c403e65a3d04754b5e1559f48a32b46fb81ef94a4


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3308/BoiSyncDB?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


cors.allowedOrigin=http://localhost:5173